spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aphexa_discovery_db
    username: aphexa_user
    password: aphexa_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
